name: "Update Bundled PBI Visuals"
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update-libs:
    name: "Update Bundled PBI Visuals"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v6

    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        BRANCH=update-libs-$(echo $RANDOM | md5sum | head -c 10; echo)
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        git checkout -b $BRANCH

    - name: Update SPC lib
      id: spc-update
      uses: ./.github/actions/upgrade-pbi-lib
      with:
        type: "SPC"

    - name: Update Funnel lib
      id: funnel-update
      uses: ./.github/actions/upgrade-pbi-lib
      with:
        type: "Funnel"

    - name: Generate PR
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.spc-update.outputs.visual-updated == 'true' || steps.funnel-update.outputs.visual-updated == 'true'
      run: |
        # Generate PR Title
        TITLE="Update Bundled Lib(s): "
        if [ "${{ steps.spc-update.outputs.visual-updated }}" == "true" ]; then
          TITLE+="PBISPC to ${{ steps.spc-update.outputs.visual-version }}, "
        fi
        if [ "${{ steps.funnel-update.outputs.visual-updated }}" == "true" ]; then
          TITLE+="PBIFUN to ${{ steps.funnel-update.outputs.visual-version }}"
        fi

        # Increment package version
        perl -i -pe 's/^Version:\s*(\d+)\.(\d+)\.(\d+)/"Version: $1.$2.".($3+1)/e' DESCRIPTION
        git add DESCRIPTION
        git commit -m "Increment package version"

        git push --set-upstream origin ${{ env.BRANCH }}
        gh pr create \
          --title "$TITLE" \
          --body "This PR was automatically created by GitHub Actions." \
          --base main \
          --head ${{ env.BRANCH }}

        gh workflow run R-CMD-check.yaml --ref ${{ env.BRANCH }}
      shell: bash
