name: "Update Bundled PBI Visuals"
on:
  workflow_dispatch:

jobs:
  update-libs:
    name: "Update Bundled PBI Visuals"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v6
      with:
        token: ${{ secrets.CONTROLCHARTS_GH_PAT }}

    - name: Configure Git
      run: |
        git config --global user.email "andrew.johnson@arjohnsonau.com"
        git config --global user.name "andrjohns"
        BRANCH=update-libs-$(echo $RANDOM | md5sum | head -c 10; echo)
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        git checkout -b $BRANCH

    - name: Update SPC lib
      id: spc-update
      uses: ./.github/actions/upgrade-pbi-lib
      with:
        type: "SPC"

    - name: Update Funnel lib
      id: funnel-update
      uses: ./.github/actions/upgrade-pbi-lib
      with:
        type: "Funnel"

    - name: Generate PR
      env:
        GH_TOKEN: ${{ secrets.CONTROLCHARTS_GH_PAT }}
      if: steps.spc-update.outputs.visual-updated == 'true' || steps.funnel-update.outputs.visual-updated == 'true'
      run: |
        TITLE="Update Bundled Lib(s): "
        if [ "${{ steps.spc-update.outputs.visual-updated }}" == "true" ]; then
          TITLE+="PBISPC to ${{ steps.spc-update.outputs.visual-version }}, "
        fi
        if [ "${{ steps.funnel-update.outputs.visual-updated }}" == "true" ]; then
          TITLE+="PBIFUN to ${{ steps.funnel-update.outputs.visual-version }}"
        fi
        git push --set-upstream origin ${{ env.BRANCH }}
        gh pr create \
          --title "$TITLE" \
          --body "This PR was automatically created by GitHub Actions." \
          --base main \
          --head ${{ env.BRANCH }}
